/**
 * NotificationEvent: an item from the backend's GET /api/notifications/recent response.
 *
 * - Generated by automatic injury/depth-chart change detection, or by an admin-sent fake push.
 * - Arrives sorted by ascending id. The FE persists the last-seen id in localStorage so that
 *   on reconnect it only catches up on events after that id.
 */
export type NotificationEvent = {
  id: number;
  event_type: string;          // "INJURY" | "DEPTH" | "NEWS" etc
  player_id: string;
  player_name: string | null;
  message: string;
  created_at: string;          // ISO 8601
};
